export const CURRENCY_LIST_REQUEST = 'CURRENCY_LIST_REQUEST';
export const CURRENCY_LIST_SUCCESS = 'CURRENCY_LIST_SUCCESS';
export const CURRENCY_LIST_FAIL = 'CURRENCY_LIST_FAIL';

export const CURRENT_EXCHANGER_REQUEST = 'CURRENT_EXCHANGER_REQUEST';
export const CURRENT_EXCHANGER_SUCCESS = 'CURRENT_EXCHANGER_SUCCESS';
export const CURRENT_EXCHANGER_FAIL = 'CURRENT_EXCHANGER_FAIL';